apiVersion: v1
kind: ConfigMap
metadata:
  name: jukebox-config
  namespace: jukebox
data:
  JUKEBOX_COOKIE_SECURE: "true"
  JUKEBOX_FRAME_ANCESTORS: "https://kiosk.rromani.eu"
  JUKEBOX_CORS_ALLOW_ORIGINS: "https://kiosk.rromani.eu"
