apiVersion: v1
kind: Secret
metadata:
  name: jukebox-secrets
  namespace: jukebox
  labels:
    app.kubernetes.io/name: jukebox
type: Opaque
stringData:
  JUKEBOX_DATABASE_URL: "REPLACE_ME"
  JUKEBOX_OPERATOR_USERNAME: "REPLACE_ME"
  JUKEBOX_OPERATOR_PASSWORD: "REPLACE_ME"
  JUKEBOX_SESSION_SECRET: "REPLACE_ME"
